### ISSUE TITLE
File Step2_Get_environmental_layers.R requires files that are not in repo

### ISSUE THREAD

**Issue by eirenjacobson** [MMARINeDNA/Valdiviaetal_2D-eDNA-spatial-distributions#2]
The following files are not in the repo, and the file Step2 does not include code to download them. 
There is a comment in the script "#Manually obtain from env layers from COPERNICUS and load them"
Can this be automated, or instructions for downloading data included?

ESV_surface_083_082019<-raster('./downloaded_predictors/CMEMs/USA-Coast/0-0083/1_August/surface/tif/ESV.tif')
epi_surface_083_022019<-raster('./downloaded_predictors/CMEMs/USA-Coast/0-0083/1_August/surface/tif/epi.tif')
lmeso_surface_083_022019<-raster('./downloaded_predictors/CMEMs/USA-Coast/0-0083/1_August/surface/tif/lmeso.tif')
umeso_surface_083_022019<-raster('./downloaded_predictors/CMEMs/USA-Coast/0-0083/1_August/surface/tif/umeso.tif')
zooc_surface_083_022019<-raster('./downloaded_predictors/CMEMs/USA-Coast/0-0083/1_August/surface/tif/zooc.tif')
zeu_surface_083_022019<-raster('./downloaded_predictors/CMEMs/USA-Coast/0-0083/1_August/surface/tif/zeu.tif')
npp_surface_083_082019<-raster('./downloaded_predictors/CMEMs/USA-Coast/0-0083/1_August/surface/tif/npp.tif')
NWV_surface_083_082019<-raster('./downloaded_predictors/CMEMs/USA-Coast/0-0083/1_August/surface/tif/NWV.tif')
OML_surface_083_082019<-raster('./downloaded_predictors/CMEMs/USA-Coast/0-0083/1_August/surface/tif/OML.tif')
pelagicL_depth_surface_083_082019<-raster('./downloaded_predictors/CMEMs/USA-Coast/0-0083/1_August/surface/tif/pelagicL_depth.tif')
SSH_surface_083_082019<-raster('./downloaded_predictors/SSH.tif')
SWS_surface_083_082019<-raster('./downloaded_predictors/CMEMs/USA-Coast/0-0083/1_August/surface/tif/SWS.tif')
SWT_surface_083_082019<-raster('./downloaded_predictors/SWT.tif')

**Comment by taniavaldiviac** [comment]
I added the files in ./downloaded_predictors/ and also the shape file in ./downloaded_predictors/shp/ 

The easiest way would be to have these layers in the repository, as they have already been homogenized in terms of resolution and extent.

**Comment by eirenjacobson** [comment]
I'm now able to load these files, but am having trouble putting them all together in a brick. I was getting an error message that they weren't all the same extent, so I went through and used setExtent() with your bounding box to make them all the same extent. Now I'm getting an error message that they can't all go in the same brick because they have different numbers of columns -- it looks like the first three (bathy, dist, and slope) might have a finer resolution than the other covariates?

**Comment by avancise** [comment]
Eiren - is this still an issue, or can we close this?
