### ISSUE TITLE
Missing packages?

### ISSUE THREAD

**Issue by eirenjacobson** [MMARINeDNA/Valdiviaetal_2D-eDNA-spatial-distributions#6]
Lines 81 and 84 in the Step3 script don't work for me. Do these functions (draw and auc) come from packages that aren't loaded? Or maybe from the ggsn package which I couldn't install?

**Comment by taniavaldiviac** [comment]
auc function needed the "pROC" package, I added it to the list of packages to be installed

**Comment by taniavaldiviac** [comment]
The code has been updated to include the installation and loading of the package
